"""update upload/review models and relationships

Revision ID: dabfe5379bb6
Revises: 4b1f41cccd0d
Create Date: 2025-10-23 11:30:05.231425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabfe5379bb6'
down_revision: Union[str, None] = '4b1f41cccd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('uploads', sa.Column('file_path', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'uploads', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploads', type_='foreignkey')
    op.drop_column('uploads', 'file_path')
    op.drop_column('uploads', 'user_id')
    # ### end Alembic commands ###
